In [7]:
# obtain distance_to_edge file

data <- read.csv(file = "distance_to_edge.csv")
data

    ChrI.213 ChrX.227 ChrX.227.male
1     0      322       232
2     0      343       428
3     0      380       474
4    43      411       569
5    47      440       666
6    48      459       750
7    51      468       791
8    55      478       811
9    56      519       883
10   65      561       894
11   65      577       921
12   82      583       925
13   84      621       947
14   95      631       953
15  112      649       958
16  115      694       966
17  124      714      1022
18  147      730      1030
19  154      732      1035
20  161      749      1054
21  164      752      1074
22  167      766      1079
23  177      798      1090
24  210      814      1091
25  221      827      1093
26  280      869      1099
27  291      884      1100
28  301      900      1104
29  306      900      1105
30  339      903      1114
... ...      ...      ...
35   401      946     1222
36   402      970     1252
37   406      975     1254
38   416      991     1267
39   417      997     1269
40   421     1016     1272
41   426     1018     1274
42   435     1037     1294
43   466     1040     1294
44   484     1061     1311
45   491     1067     1334
46   501     1097     1340
47   509     1113     1341
48   514     1121     1343
49   556     1142     1360
50   626     1168     1387
51   631     1180     1395
52   694     1241     1396
53   813     1261     1402
54   814     1268     1414
55   932     1268     1477
56  1027     1347     1520
57  1037     1388     1535
58  1078     1420     1551
59  1131     1421     1556
60  1164     1444     1619
61  1210     1488       NA
62  1449     1544       NA
63    NA     1546       NA
64    NA     1662       NA

In [10]:
# compare ChrX 227 and ChrX 227 male using Welch's two sample t-test

t_test_result <- t.test(data[2], data[3])
print(t_test_result)

	Welch Two Sample t-test

data:  data[2] and data[3]
t = -3.5816, df = 121.32, p-value = 0.0004924
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -307.36339  -88.53244
sample estimates:
mean of x mean of y
 928.2188 1126.1667